services:
  - type: web
    name: thesis-delay-predictor
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=10000
    workingDir: service
    autoDeploy: false
